- docs:
    - introduction: index.md
    - VS-of-linear-structure-and-nonlinear-structure: VS-of-linear-structure-and-nonlinear-structure.md
    - VS-of-trees: VS-of-tree.md
    - VS-of-graph-and-tree.md: VS-of-graph-and-tree.md
    - VS-of-implementation-of-ADT: VS-of-implementation-of-ADT.md
    - VS-of-search-tree-and-hash-table: VS-of-search-tree-and-hash-table.md
    - VS-of-search-tree-and-skip-list: VS-of-search-tree-and-skip-list.md
    - TODO: TODO.md