nav:
    - Introduction: index.md
    - Structure: Structure.md
    - Relation: Relation.md
    - Transitive-relation: Transitive-relation.md
    - Hierarchy: Hierarchy.md
    - Chain: Chain.md
    - Describe-structure: Describe-structure.md