docs:
    - introduction: index.md
    - structure: structure.md
    - wikipedia-Data-structure:
        - Data-structure: wikipedia-Data-structure.md
        - Implicit-data-structure: wikipedia-Implicit-data-structure.md
    - ADT: None
    - array: None
    - list: None
    - graph: None
    - tree: None
    - hash: None
    - probabilistic-data-structures: None
    - summary-of-data-structure: None
    - TODO: TODO.md
others: None