docs:
    - Home: index.md
    - Structure: structure.md
    - Data-structure: None
    - ADT: None
    - Array: None
    - List: None
    - Graph: None
    - Tree: None
    - Hash: None
    - Probabilistic-data-structures: None
    - Summary-of-data-structure: None
    - TODO: TODO.md
others: None